name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - src/**
      - CMakeLists.txt

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.14.0

    - name: Test
      run: ./scripts/test.sh
