name: Test

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - src/**
      - CMakeLists.txt

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GoogleTest
        uses: Bacondish2023/setup-googletest@v1
        with:
          tag: v1.14.0

      - name: Test
        run: ./test.sh
